---
title: "02 Supervised ML"
date: "2020-11-05"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```


```{r libraries}
library(tidyverse)
library(tidymodels)
library(parsnip)
library(recipes)
library(rsample)
library(yardstick)
library(rpart.plot)
```

```{r model, feature eng}
model_01_linear_lm_simple <- linear_reg(mode = "regression") %>%
  set_engine("lm") 

#bike_orderlines_tbl <- readRDS("./02_ml_sup_files/bike_orderlines.rds")
#bike_orderlines_tbl %>%
#glimpse()

bike_features_tbl <- readRDS("./02_ml_sup_files/bike_features_tbl.rds")

bike_features_tbl <- bike_features_tbl %>%
  select(model:url, `Rear Derailleur`, `Shift Lever`) %>%
  set_names(str_replace_all(names(train_tbl), " |-", "_"))
```

```{r split}
set.seed(seed = 1113)
bike_split_obj <- initial_split(bike_features_tbl,
                            strata = category_2)
#bike_split_obj %>% training() %>% distinct(category_2)
#bike_split_obj %>% testing() %>% distinct(category_2)

train_tbl <- training(bike_split_obj)
test_tbl <- testing(bike_split_obj)

recipe_obj <- recipe(price ~ ., data = bike_features_tbl) %>%
  step_rm(url) %>%
  step_dummy(all_nominal(), one_hot = TRUE) %>%
  prep(training = train_tbl)

bikes_wflow <- 
  workflow() %>% 
  add_model(model_01_linear_lm_simple) %>% 
  add_recipe(recipe_obj)

bikes_fit <-
  bikes_wflow %>%
  fit(data = train_tbl)

calc_metrics <- function(model, new_data = test_tbl) {

    model %>%
        predict(new_data = new_data) %>%

        bind_cols(new_data %>% select(price)) %>%
        yardstick::metrics(truth = price, estimate = .pred)

}

bikes_fit %>%
  calc_metrics
```
