project:
  type: website
  # output-dir: docs


website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Machine Learning Fundamentals "
            file: content/01_journal/01_tidyverse.qmd
          - text: "02 Supervised Machine Learning (II)"
            file: content/01_journal/02_data_acquisition.qmd
          - text: "03 Automated Machine Learning with H2O (I)"
            file: content/01_journal/03_data_wrangling.qmd
          - text: "04 Automated Machine Learning with H2O (II) and Performance Measures"
            file: content/01_journal/04_data_visualization.qmd
          - text: "05 LIME "
            file: content/01_journal/05_lime.qmd
          - text: "06 Deep Learning"
            file: content/01_journal/06_deep_learning.qmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto